package contentful

const (
	TopicContentTypeCreate    = "ContentManagement.ContentType.create"
	TopicContentTypeSave      = "ContentManagement.ContentType.save"
	TopicContentTypePublish   = "ContentManagement.ContentType.publish"
	TopicContentTypeUnpublish = "ContentManagement.ContentType.unpublish"
	TopicContentTypeDelete    = "ContentManagement.ContentType.delete"
	TopicEntryCreate          = "ContentManagement.Entry.create"
	TopicEntrySave            = "ContentManagement.Entry.save"
	TopicEntryAutoSave        = "ContentManagement.Entry.auto_save"
	TopicEntryArchive         = "ContentManagement.Entry.archive"
	TopicEntryUnarchive       = "ContentManagement.Entry.unarchive"
	TopicEntryPublish         = "ContentManagement.Entry.publish"
	TopicEntryUnpublish       = "ContentManagement.Entry.unpublish"
	TopicEntryDelete          = "ContentManagement.Entry.delete"
	TopicAssetCreate          = "ContentManagement.Asset.create"
	TopicAssetSave            = "ContentManagement.Asset.save"
	TopicAssetAutoSave        = "ContentManagement.Asset.auto_save"
	TopicAssetArchive         = "ContentManagement.Asset.archive"
	TopicAssetUnarchive       = "ContentManagement.Asset.unarchive"
	TopicAssetPublish         = "ContentManagement.Asset.publish"
	TopicAssetUnpublish       = "ContentManagement.Asset.unpublish"
	TopicAssetDelete          = "ContentManagement.Asset.delete"
)
